#############################################################################
# Makefile for building: /tmp/adam_j4/serwer_graficzny/serwer_graficzny
# Generated by qmake (3.1) (Qt 5.9.7)
# Project:  /tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro
# Template: app
# Command: /home/adam_j4/anaconda3/bin/qmake -o Makefile.app /tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro
#############################################################################

MAKEFILE      = Makefile.app

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_OPENGL_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -std=c++17 -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I/tmp/adam_j4/serwer_graficzny/out/pro -I. -Iinc -I/home/adam_j4/anaconda3/include/qt -I/home/adam_j4/anaconda3/include/qt/QtOpenGL -I/home/adam_j4/anaconda3/include/qt/QtWidgets -I/home/adam_j4/anaconda3/include/qt/QtGui -I/home/adam_j4/anaconda3/include/qt/QtXml -I/home/adam_j4/anaconda3/include/qt/QtCore -I/tmp/adam_j4/serwer_graficzny/out/moc -I/home/adam_j4/anaconda3/mkspecs/linux-g++
QMAKE         = /home/adam_j4/anaconda3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /home/adam_j4/anaconda3/bin/qmake -install qinstall
QINSTALL_PROGRAM = /home/adam_j4/anaconda3/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = serwer_graficzny1.0.0
DISTDIR = /tmp/adam_j4/serwer_graficzny/out/obj/serwer_graficzny1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/home/adam_j4/anaconda3/lib
LIBS          = $(SUBLIBS) -lQGLViewer-qt5 -lSOIL -L/home/adam_j4/anaconda3/lib -lQt5OpenGL -lQt5Widgets -lQt5Gui -lQt5Xml -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = /tmp/adam_j4/serwer_graficzny/out/obj/

####### Files

SOURCES       = src/gsv-BufferedScene.cpp \
		src/gsv-CommandBuffer.cpp \
		src/gsv-CommandInterpreter.cpp \
		src/gsv-Cuboid.cpp \
		src/gsv-GeomParams.cpp \
		src/gsv-GraphObject.cpp \
		src/gsv-GraphicsWindow.cpp \
		src/gsv-Map4DescGeomObjs.cpp \
		src/gsv-Map4SceneGeomObjs.cpp \
		src/gsv-Scene.cpp \
		src/gsv-SceneServer.cpp \
		src/gsv-ServerCommand.cpp \
		src/gsv-Tests.cpp \
		src/gsv-WgViewer3D.cpp \
		src/gtsDebug.cpp \
		src/main.cpp /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp \
		/tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp
OBJECTS       = /tmp/adam_j4/serwer_graficzny/out/obj/gsv-BufferedScene.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-CommandBuffer.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-CommandInterpreter.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Cuboid.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-GeomParams.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-GraphObject.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-GraphicsWindow.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Map4DescGeomObjs.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Map4SceneGeomObjs.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Scene.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-SceneServer.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-ServerCommand.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Tests.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gsv-WgViewer3D.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/gtsDebug.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/main.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/moc_gsv-GraphicsWindow.o \
		/tmp/adam_j4/serwer_graficzny/out/obj/moc_gsv-WgViewer3D.o
DIST          = /home/adam_j4/anaconda3/mkspecs/features/spec_pre.prf \
		/home/adam_j4/anaconda3/mkspecs/common/unix.conf \
		/home/adam_j4/anaconda3/mkspecs/common/linux.conf \
		/home/adam_j4/anaconda3/mkspecs/common/sanitize.conf \
		/home/adam_j4/anaconda3/mkspecs/common/gcc-base.conf \
		/home/adam_j4/anaconda3/mkspecs/common/gcc-base-unix.conf \
		/home/adam_j4/anaconda3/mkspecs/common/g++-base.conf \
		/home/adam_j4/anaconda3/mkspecs/common/g++-unix.conf \
		/home/adam_j4/anaconda3/mkspecs/qconfig.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/adam_j4/anaconda3/mkspecs/features/qt_functions.prf \
		/home/adam_j4/anaconda3/mkspecs/features/qt_config.prf \
		/home/adam_j4/anaconda3/mkspecs/linux-g++/qmake.conf \
		/home/adam_j4/anaconda3/mkspecs/features/spec_post.prf \
		/tmp/adam_j4/serwer_graficzny/out/pro/.qmake.stash \
		/home/adam_j4/anaconda3/mkspecs/features/exclusive_builds.prf \
		/home/adam_j4/anaconda3/mkspecs/features/toolchain.prf \
		/home/adam_j4/anaconda3/mkspecs/features/default_pre.prf \
		/home/adam_j4/anaconda3/mkspecs/features/resolve_config.prf \
		/home/adam_j4/anaconda3/mkspecs/features/default_post.prf \
		/home/adam_j4/anaconda3/mkspecs/features/warn_on.prf \
		/home/adam_j4/anaconda3/mkspecs/features/qt.prf \
		/home/adam_j4/anaconda3/mkspecs/features/resources.prf \
		/home/adam_j4/anaconda3/mkspecs/features/moc.prf \
		/home/adam_j4/anaconda3/mkspecs/features/unix/opengl.prf \
		/home/adam_j4/anaconda3/mkspecs/features/uic.prf \
		/home/adam_j4/anaconda3/mkspecs/features/unix/thread.prf \
		/home/adam_j4/anaconda3/mkspecs/features/qmake_use.prf \
		/home/adam_j4/anaconda3/mkspecs/features/file_copies.prf \
		/home/adam_j4/anaconda3/mkspecs/features/testcase_targets.prf \
		/home/adam_j4/anaconda3/mkspecs/features/exceptions.prf \
		/home/adam_j4/anaconda3/mkspecs/features/yacc.prf \
		/home/adam_j4/anaconda3/mkspecs/features/lex.prf \
		/tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro inc/geomVector.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-Cuboid.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-GraphicsWindow.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Scene.hh \
		inc/gsv-SceneServer.hh \
		inc/gsv-ServerCommand.hh \
		inc/gsv-Vector3d.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-WgViewer3D.hh \
		inc/gtsDebug.hh src/gsv-BufferedScene.cpp \
		src/gsv-CommandBuffer.cpp \
		src/gsv-CommandInterpreter.cpp \
		src/gsv-Cuboid.cpp \
		src/gsv-GeomParams.cpp \
		src/gsv-GraphObject.cpp \
		src/gsv-GraphicsWindow.cpp \
		src/gsv-Map4DescGeomObjs.cpp \
		src/gsv-Map4SceneGeomObjs.cpp \
		src/gsv-Scene.cpp \
		src/gsv-SceneServer.cpp \
		src/gsv-ServerCommand.cpp \
		src/gsv-Tests.cpp \
		src/gsv-WgViewer3D.cpp \
		src/gtsDebug.cpp \
		src/main.cpp
QMAKE_TARGET  = serwer_graficzny
DESTDIR       = /tmp/adam_j4/serwer_graficzny/
TARGET        = /tmp/adam_j4/serwer_graficzny/serwer_graficzny


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	@test -d /tmp/adam_j4/serwer_graficzny/ || mkdir -p /tmp/adam_j4/serwer_graficzny/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile.app: /tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro /home/adam_j4/anaconda3/mkspecs/linux-g++/qmake.conf /home/adam_j4/anaconda3/mkspecs/features/spec_pre.prf \
		/home/adam_j4/anaconda3/mkspecs/common/unix.conf \
		/home/adam_j4/anaconda3/mkspecs/common/linux.conf \
		/home/adam_j4/anaconda3/mkspecs/common/sanitize.conf \
		/home/adam_j4/anaconda3/mkspecs/common/gcc-base.conf \
		/home/adam_j4/anaconda3/mkspecs/common/gcc-base-unix.conf \
		/home/adam_j4/anaconda3/mkspecs/common/g++-base.conf \
		/home/adam_j4/anaconda3/mkspecs/common/g++-unix.conf \
		/home/adam_j4/anaconda3/mkspecs/qconfig.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3danimation.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dcore.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dextras.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dinput.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquick.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3drender.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_charts.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_charts_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_concurrent.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_core.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_core_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_dbus.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designer.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designer_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gamepad.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gui.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gui_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_help.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_help_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_location.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_location_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimedia.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_network.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_network_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_networkauth.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_nfc.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_opengl.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_positioning.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_printsupport.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_purchasing.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qml.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qml_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmltest.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quick.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quick_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_repparser.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_script.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_script_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scripttools.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scxml.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sensors.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialbus.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialport.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sql.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sql_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_svg.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_svg_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_testlib.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uitools.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webchannel.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webengine.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_websockets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webview.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webview_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_widgets.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_x11extras.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xml.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xml_private.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/home/adam_j4/anaconda3/mkspecs/features/qt_functions.prf \
		/home/adam_j4/anaconda3/mkspecs/features/qt_config.prf \
		/home/adam_j4/anaconda3/mkspecs/linux-g++/qmake.conf \
		/home/adam_j4/anaconda3/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/home/adam_j4/anaconda3/mkspecs/features/exclusive_builds.prf \
		/home/adam_j4/anaconda3/mkspecs/features/toolchain.prf \
		/home/adam_j4/anaconda3/mkspecs/features/default_pre.prf \
		/home/adam_j4/anaconda3/mkspecs/features/resolve_config.prf \
		/home/adam_j4/anaconda3/mkspecs/features/default_post.prf \
		/home/adam_j4/anaconda3/mkspecs/features/warn_on.prf \
		/home/adam_j4/anaconda3/mkspecs/features/qt.prf \
		/home/adam_j4/anaconda3/mkspecs/features/resources.prf \
		/home/adam_j4/anaconda3/mkspecs/features/moc.prf \
		/home/adam_j4/anaconda3/mkspecs/features/unix/opengl.prf \
		/home/adam_j4/anaconda3/mkspecs/features/uic.prf \
		/home/adam_j4/anaconda3/mkspecs/features/unix/thread.prf \
		/home/adam_j4/anaconda3/mkspecs/features/qmake_use.prf \
		/home/adam_j4/anaconda3/mkspecs/features/file_copies.prf \
		/home/adam_j4/anaconda3/mkspecs/features/testcase_targets.prf \
		/home/adam_j4/anaconda3/mkspecs/features/exceptions.prf \
		/home/adam_j4/anaconda3/mkspecs/features/yacc.prf \
		/home/adam_j4/anaconda3/mkspecs/features/lex.prf \
		/tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro \
		/usr/lib/x86_64-linux-gnu/libQGLViewer-qt5.prl \
		/home/adam_j4/anaconda3/lib/libQt5OpenGL.prl \
		/home/adam_j4/anaconda3/lib/libQt5Widgets.prl \
		/home/adam_j4/anaconda3/lib/libQt5Gui.prl \
		/home/adam_j4/anaconda3/lib/libQt5Xml.prl \
		/home/adam_j4/anaconda3/lib/libQt5Core.prl
	$(QMAKE) -o Makefile.app /tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro
/home/adam_j4/anaconda3/mkspecs/features/spec_pre.prf:
/home/adam_j4/anaconda3/mkspecs/common/unix.conf:
/home/adam_j4/anaconda3/mkspecs/common/linux.conf:
/home/adam_j4/anaconda3/mkspecs/common/sanitize.conf:
/home/adam_j4/anaconda3/mkspecs/common/gcc-base.conf:
/home/adam_j4/anaconda3/mkspecs/common/gcc-base-unix.conf:
/home/adam_j4/anaconda3/mkspecs/common/g++-base.conf:
/home/adam_j4/anaconda3/mkspecs/common/g++-unix.conf:
/home/adam_j4/anaconda3/mkspecs/qconfig.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3danimation.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3danimation_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dcore.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dcore_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dextras.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dextras_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dinput.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dinput_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dlogic.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquick.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquick_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickanimation.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickextras.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickinput.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickrender.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3drender.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_3drender_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bluetooth.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_charts.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_charts_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_concurrent.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_concurrent_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_core.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_core_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_datavisualization.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_datavisualization_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_dbus.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_dbus_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designer.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designer_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_designercomponents_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_egl_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_fb_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gamepad.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gamepad_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_glx_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gui.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_gui_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_help.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_help_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_input_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_location.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_location_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimedia.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimedia_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_network.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_network_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_networkauth.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_networkauth_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_nfc.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_nfc_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_opengl.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_opengl_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_openglextensions.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_positioning.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_positioning_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_printsupport.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_printsupport_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_purchasing.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_purchasing_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qml.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qml_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmldebug_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmltest.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qmltest_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quick.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quick_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickcontrols2.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickwidgets.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_remoteobjects.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_repparser.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_repparser_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_script.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_script_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scripttools.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scripttools_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scxml.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_scxml_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sensors.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sensors_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialbus.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialbus_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialport.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_serialport_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_service_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sql.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_sql_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_svg.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_svg_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_testlib.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_testlib_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_texttospeech.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_texttospeech_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_theme_support_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uiplugin.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uitools.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_uitools_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webchannel.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webchannel_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webengine.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webengine_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecore.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecore_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginewidgets.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_websockets.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_websockets_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webview.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_webview_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_widgets.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_widgets_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_x11extras.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_x11extras_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xml.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xml_private.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/home/adam_j4/anaconda3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/home/adam_j4/anaconda3/mkspecs/features/qt_functions.prf:
/home/adam_j4/anaconda3/mkspecs/features/qt_config.prf:
/home/adam_j4/anaconda3/mkspecs/linux-g++/qmake.conf:
/home/adam_j4/anaconda3/mkspecs/features/spec_post.prf:
.qmake.stash:
/home/adam_j4/anaconda3/mkspecs/features/exclusive_builds.prf:
/home/adam_j4/anaconda3/mkspecs/features/toolchain.prf:
/home/adam_j4/anaconda3/mkspecs/features/default_pre.prf:
/home/adam_j4/anaconda3/mkspecs/features/resolve_config.prf:
/home/adam_j4/anaconda3/mkspecs/features/default_post.prf:
/home/adam_j4/anaconda3/mkspecs/features/warn_on.prf:
/home/adam_j4/anaconda3/mkspecs/features/qt.prf:
/home/adam_j4/anaconda3/mkspecs/features/resources.prf:
/home/adam_j4/anaconda3/mkspecs/features/moc.prf:
/home/adam_j4/anaconda3/mkspecs/features/unix/opengl.prf:
/home/adam_j4/anaconda3/mkspecs/features/uic.prf:
/home/adam_j4/anaconda3/mkspecs/features/unix/thread.prf:
/home/adam_j4/anaconda3/mkspecs/features/qmake_use.prf:
/home/adam_j4/anaconda3/mkspecs/features/file_copies.prf:
/home/adam_j4/anaconda3/mkspecs/features/testcase_targets.prf:
/home/adam_j4/anaconda3/mkspecs/features/exceptions.prf:
/home/adam_j4/anaconda3/mkspecs/features/yacc.prf:
/home/adam_j4/anaconda3/mkspecs/features/lex.prf:
/tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro:
/usr/lib/x86_64-linux-gnu/libQGLViewer-qt5.prl:
/home/adam_j4/anaconda3/lib/libQt5OpenGL.prl:
/home/adam_j4/anaconda3/lib/libQt5Widgets.prl:
/home/adam_j4/anaconda3/lib/libQt5Gui.prl:
/home/adam_j4/anaconda3/lib/libQt5Xml.prl:
/home/adam_j4/anaconda3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile.app /tmp/adam_j4/serwer_graficzny/out/pro/serwer_graficzny.pro

qmake_all: FORCE


all: Makefile.app $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /home/adam_j4/anaconda3/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents inc/geomVector.hh inc/gsv-AnglesRPY.hh inc/gsv-BufferedScene.hh inc/gsv-CommandBuffer.hh inc/gsv-CommandInterpreter.hh inc/gsv-Cuboid.hh inc/gsv-GeomParams.hh inc/gsv-GraphObject.hh inc/gsv-GraphicsWindow.hh inc/gsv-Map4DescGeomObjs.hh inc/gsv-Map4SceneGeomObjs.hh inc/gsv-RGB.hh inc/gsv-Scene.hh inc/gsv-SceneServer.hh inc/gsv-ServerCommand.hh inc/gsv-Vector3d.hh inc/gsv-Vector3i.hh inc/gsv-WgViewer3D.hh inc/gtsDebug.hh $(DISTDIR)/
	$(COPY_FILE) --parents src/gsv-BufferedScene.cpp src/gsv-CommandBuffer.cpp src/gsv-CommandInterpreter.cpp src/gsv-Cuboid.cpp src/gsv-GeomParams.cpp src/gsv-GraphObject.cpp src/gsv-GraphicsWindow.cpp src/gsv-Map4DescGeomObjs.cpp src/gsv-Map4SceneGeomObjs.cpp src/gsv-Scene.cpp src/gsv-SceneServer.cpp src/gsv-ServerCommand.cpp src/gsv-Tests.cpp src/gsv-WgViewer3D.cpp src/gtsDebug.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile.app


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: /tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) /tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h
/tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h: /home/adam_j4/anaconda3/mkspecs/features/data/dummy.cpp
	g++ -pipe -std=c++17 -O2 -Wall -W -dM -E -o /tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h /home/adam_j4/anaconda3/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp
/tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp: /home/adam_j4/anaconda3/include/qt/QtWidgets/QWidget \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtcore-config.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsysinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlogging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qflags.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmutex.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnumeric.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qversiontagging.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtgui-config.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnamespace.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstring.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qchar.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrefcount.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qarraydata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qalgorithms.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiterator.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpair.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qregexp.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcoreevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmetatype.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmargins.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrect.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsize.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpoint.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpalette.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qcolor.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qrgb.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qrgba64.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qbrush.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvector.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qmatrix.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpolygon.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qregion.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qdatastream.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiodevice.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qline.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtransform.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpainterpath.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qimage.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpixelformat.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpixmap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qshareddata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhash.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfont.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfontinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qcursor.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qkeysequence.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvariant.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qdebug.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtextstream.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlocale.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qset.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qurl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qurlquery.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qfile.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qfiledevice.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qvector2d.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QMainWindow \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qicon.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/QTimer \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasictimer.h \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-GraphicsWindow.hh \
		/tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h \
		/home/adam_j4/anaconda3/bin/moc
	/home/adam_j4/anaconda3/bin/moc $(DEFINES) --include /tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h -I/home/adam_j4/anaconda3/mkspecs/linux-g++ -I/tmp/adam_j4/serwer_graficzny/out/pro -I/tmp/adam_j4/serwer_graficzny/out/pro/inc -I/home/adam_j4/anaconda3/include/qt -I/home/adam_j4/anaconda3/include/qt/QtOpenGL -I/home/adam_j4/anaconda3/include/qt/QtWidgets -I/home/adam_j4/anaconda3/include/qt/QtGui -I/home/adam_j4/anaconda3/include/qt/QtXml -I/home/adam_j4/anaconda3/include/qt/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/gsv-GraphicsWindow.hh -o /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp

/tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp: /home/adam_j4/anaconda3/include/qt/QtCore/QTimer \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtcore-config.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsysinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlogging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qflags.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmutex.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnumeric.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qversiontagging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasictimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnamespace.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstring.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qchar.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrefcount.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qarraydata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qalgorithms.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiterator.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpair.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qregexp.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcoreevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmetatype.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject_impl.h \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-WgViewer3D.hh \
		/tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h \
		/home/adam_j4/anaconda3/bin/moc
	/home/adam_j4/anaconda3/bin/moc $(DEFINES) --include /tmp/adam_j4/serwer_graficzny/out/moc/moc_predefs.h -I/home/adam_j4/anaconda3/mkspecs/linux-g++ -I/tmp/adam_j4/serwer_graficzny/out/pro -I/tmp/adam_j4/serwer_graficzny/out/pro/inc -I/home/adam_j4/anaconda3/include/qt -I/home/adam_j4/anaconda3/include/qt/QtOpenGL -I/home/adam_j4/anaconda3/include/qt/QtWidgets -I/home/adam_j4/anaconda3/include/qt/QtGui -I/home/adam_j4/anaconda3/include/qt/QtXml -I/home/adam_j4/anaconda3/include/qt/QtCore -I. -I/usr/include/c++/7 -I/usr/include/x86_64-linux-gnu/c++/7 -I/usr/include/c++/7/backward -I/usr/lib/gcc/x86_64-linux-gnu/7/include -I/usr/local/include -I/usr/lib/gcc/x86_64-linux-gnu/7/include-fixed -I/usr/include/x86_64-linux-gnu -I/usr/include inc/gsv-WgViewer3D.hh -o /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-BufferedScene.o: src/gsv-BufferedScene.cpp inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-BufferedScene.o src/gsv-BufferedScene.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-CommandBuffer.o: src/gsv-CommandBuffer.cpp inc/gsv-CommandBuffer.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-CommandBuffer.o src/gsv-CommandBuffer.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-CommandInterpreter.o: src/gsv-CommandInterpreter.cpp inc/gtsDebug.hh \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-ServerCommand.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-CommandInterpreter.o src/gsv-CommandInterpreter.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Cuboid.o: src/gsv-Cuboid.cpp inc/gsv-Cuboid.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-Cuboid.o src/gsv-Cuboid.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-GeomParams.o: src/gsv-GeomParams.cpp inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-GeomParams.o src/gsv-GeomParams.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-GraphObject.o: src/gsv-GraphObject.cpp inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-GraphObject.o src/gsv-GraphObject.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-GraphicsWindow.o: src/gsv-GraphicsWindow.cpp /home/adam_j4/anaconda3/include/qt/QtWidgets/QStatusBar \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qstatusbar.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtcore-config.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsysinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlogging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qflags.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmutex.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnumeric.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qversiontagging.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtgui-config.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnamespace.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstring.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qchar.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrefcount.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qarraydata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qalgorithms.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiterator.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpair.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qregexp.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcoreevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmetatype.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmargins.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrect.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsize.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpoint.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpalette.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qcolor.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qrgb.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qrgba64.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qbrush.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvector.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qmatrix.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpolygon.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qregion.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qdatastream.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiodevice.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qline.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtransform.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpainterpath.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qimage.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpixelformat.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpixmap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qshareddata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhash.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfont.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfontinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qcursor.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qkeysequence.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvariant.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qdebug.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtextstream.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlocale.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qset.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qurl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qurlquery.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qfile.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qfiledevice.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qvector2d.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtouchdevice.h \
		inc/gsv-GraphicsWindow.hh \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QWidget \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QMainWindow \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qicon.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/QTimer \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasictimer.h \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-WgViewer3D.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-GraphicsWindow.o src/gsv-GraphicsWindow.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Map4DescGeomObjs.o: src/gsv-Map4DescGeomObjs.cpp inc/gsv-Map4DescGeomObjs.hh \
		inc/gtsDebug.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-Map4DescGeomObjs.o src/gsv-Map4DescGeomObjs.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Map4SceneGeomObjs.o: src/gsv-Map4SceneGeomObjs.cpp inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gtsDebug.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-Map4SceneGeomObjs.o src/gsv-Map4SceneGeomObjs.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Scene.o: src/gsv-Scene.cpp inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-Cuboid.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-Scene.o src/gsv-Scene.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-SceneServer.o: src/gsv-SceneServer.cpp inc/gsv-SceneServer.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-ServerCommand.hh \
		inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-SceneServer.o src/gsv-SceneServer.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-ServerCommand.o: src/gsv-ServerCommand.cpp inc/gsv-ServerCommand.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-Cuboid.hh \
		inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-ServerCommand.o src/gsv-ServerCommand.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-Tests.o: src/gsv-Tests.cpp inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-ServerCommand.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-Map4SceneGeomObjs.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-Tests.o src/gsv-Tests.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gsv-WgViewer3D.o: src/gsv-WgViewer3D.cpp inc/gsv-WgViewer3D.hh \
		/home/adam_j4/anaconda3/include/qt/QtCore/QTimer \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtcore-config.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsysinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlogging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qflags.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmutex.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnumeric.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qversiontagging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasictimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnamespace.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstring.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qchar.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrefcount.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qarraydata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qalgorithms.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiterator.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpair.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qregexp.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcoreevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmetatype.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject_impl.h \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-BackgroundImage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gsv-WgViewer3D.o src/gsv-WgViewer3D.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/gtsDebug.o: src/gtsDebug.cpp inc/gtsDebug.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/gtsDebug.o src/gtsDebug.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/main.o: src/main.cpp /home/adam_j4/anaconda3/include/qt/QtWidgets/QApplication \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qapplication.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtwidgetsglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtguiglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobal.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig-bootstrapped.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qconfig.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtcore-config.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsystemdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qprocessordetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcompilerdetection.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtypeinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsysinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlogging.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qflags.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasicatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_bootstrap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qgenericatomic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_cxx11.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qatomic_msvc.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qglobalstatic.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmutex.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnumeric.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qversiontagging.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtgui-config.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtwidgets-config.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcoreapplication.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstring.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qchar.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrefcount.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qnamespace.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qarraydata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringbuilder.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobjectdefs_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qalgorithms.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiterator.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhashfunctions.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpair.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbytearraylist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringlist.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qregexp.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qstringmatcher.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcoreevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qscopedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmetatype.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvarlengtharray.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontainerfwd.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qobject_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qeventloop.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qwindowdefs.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qwindowdefs_win.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qpoint.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsize.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qcursor.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qdesktopwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmargins.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpaintdevice.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qrect.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpalette.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qcolor.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qrgb.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qrgba64.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qbrush.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvector.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qmatrix.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpolygon.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qregion.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qdatastream.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qiodevice.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qline.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtransform.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpainterpath.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qimage.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpixelformat.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qpixmap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsharedpointer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qshareddata.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qhash.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qsharedpointer_impl.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfont.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfontmetrics.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qfontinfo.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qsizepolicy.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qkeysequence.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qevent.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qvariant.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qmap.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qdebug.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtextstream.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qlocale.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qset.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qcontiguouscache.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qurl.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qurlquery.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qfile.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qfiledevice.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qvector2d.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qtouchdevice.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qguiapplication.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qinputmethod.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QMainWindow \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qmainwindow.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qtabwidget.h \
		/home/adam_j4/anaconda3/include/qt/QtGui/qicon.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QHBoxLayout \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qboxlayout.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qlayout.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qlayoutitem.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qgridlayout.h \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QStatusBar \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/qstatusbar.h \
		inc/gsv-CommandInterpreter.hh \
		inc/gsv-BufferedScene.hh \
		inc/gsv-Scene.hh \
		inc/gsv-GraphObject.hh \
		inc/gsv-Map4DescGeomObjs.hh \
		inc/gsv-GeomParams.hh \
		inc/gsv-Vector3d.hh \
		inc/geomVector.hh \
		inc/gsv-RGB.hh \
		inc/gsv-Vector3i.hh \
		inc/gsv-AnglesRPY.hh \
		inc/gsv-Map4SceneGeomObjs.hh \
		inc/gsv-CommandBuffer.hh \
		inc/gsv-ServerCommand.hh \
		inc/gsv-WgViewer3D.hh \
		/home/adam_j4/anaconda3/include/qt/QtCore/QTimer \
		/home/adam_j4/anaconda3/include/qt/QtCore/qtimer.h \
		/home/adam_j4/anaconda3/include/qt/QtCore/qbasictimer.h \
		inc/gsv-SceneServer.hh \
		inc/gtsDebug.hh \
		inc/gsv-Const.h \
		inc/gsv-GraphicsWindow.hh \
		/home/adam_j4/anaconda3/include/qt/QtWidgets/QWidget
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/main.o src/main.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/moc_gsv-GraphicsWindow.o: /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/moc_gsv-GraphicsWindow.o /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-GraphicsWindow.cpp

/tmp/adam_j4/serwer_graficzny/out/obj/moc_gsv-WgViewer3D.o: /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o /tmp/adam_j4/serwer_graficzny/out/obj/moc_gsv-WgViewer3D.o /tmp/adam_j4/serwer_graficzny/out/moc/moc_gsv-WgViewer3D.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

